name: Build DLL

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '**/*.sln'
      - '**/*.cpp'
      - '**/*.h'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Visual Studio 2022
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 'latest'
        msbuild-architecture: 'x64'

    - name: Install dependencies
      run: choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional"

    - name: Build solution
      run: msbuild.exe PalWorld-NetCrack-NuLL-master/DX11-Base.sln /p:Configuration=Release

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dll-build
        path: PalWorld-NetCrack-NuLL-master/Release/  # Adjust this path to match the location of your DLLs
